# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12a44a7bba68278c9e386dc9c98a0bf70eb08c21545b16c6d3d17c27d3f96f4c85c9da7179da4157e96d300a07368a5a3e551e2c8c108cafb433908b82883ca9

test:
  secret_key_base: 12cd8760f38bb82078d617ff26c3db1f9890b74b1f02519dfd5fdc630404d428b14409e778a9950bbf3f71fa160c9fe7d4146acfb793b9780e51e1d1d2cf093e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
